version: '3.1'

services:
services:
    db:
        build: .
        ports:
            - "5435:5432"
        volumes:
            - ./.pgdata:/var/lib/postgresql/data/
        environment:
            POSTGRES_PASSWORD: password_super_segura
            POSTGRES_DB: contactask

    app:
        image: lucianofromtrelew/contactask
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - db
