version: '3.1'

services:
    db:
        image: postgres
        restart: always
        ports:
            - "5434:5432"
        volumes:
             - ./.pgdata:/var/lib/postgresql/data/
    app:
        image: lucianofromtrelew/contactask
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - db
