version: '3.1'

services:
services:
    db:
        build: ./pg
        ports:
            - "5435:5432"
        volumes:
            - ./pg/.pgdata:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: contactask
            POSTGRES_PASSWORD: password_super_segura
            POSTGRES_DB: contactask

    app:
        build: .
        restart: always
        ports:
            - "5000:5000"
        environment:
            POSTGRES_USER: contactask
            POSTGRES_PASSWORD: password_super_segura
            POSTGRES_DB: contactask
        volumes:
           - .:/usr/src/app/
        depends_on:
            - db
