version: '3.1'

services:
    db:
        image: lucianofromtrelew/contactask_db
        ports:
            - "5435:5432"
        volumes:
            - ./pg/.pgdata:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: contactask
            POSTGRES_PASSWORD: password_super_segura
            POSTGRES_DB: contactask

    app:
        image: lucianofromtrelew/contactask
        restart: always
        ports:
            - "5000:5000"
        environment:
            POSTGRES_USER: contactask
            POSTGRES_PASSWORD: password_super_segura
            POSTGRES_DB: contactask
        depends_on:
            - db
